config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  devise_for :users

  resources :users
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :public)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :age, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    %p.notice= notice
    %p.alert= alert
    %title Tutorial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if user_signed_in?
      %label= "Welcome, #{ current_user.first_name} #{ current_user.last_name }"
      = link_to 'Users', users_path
      = link_to 'Posts', posts_path
      = link_to 'Sign out', destroy_user_session_path, method: :delete
    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Title
      %th Text
      %th Author
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.text
        %td= "#{ post.user.first_name } #{ post.user.last_name }"
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Text:
  = @post.text

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :phone
    = f.text_field :phone
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th First name
      %th Last name
      %th Age
      %th Phone
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.first_name
        %td= user.last_name
        %td= user.age
        %td= user.phone
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Age:
  = @user.age
%p
  %b Phone:
  = @user.phone

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path